### ISSUE TITLE
Erklären der Begriffe Leichte Sprache, Einfache Sprache

### ISSUE THREAD

**Issue by lcalmbach** [machinelearningZH/simply-simplify-language#5]
Ich finde eure App super! Zu Beginn ist mir aufgefallen, dass mir als eher Zahlen-orienterter Mensch der Unterschied von leichter versus einfacher Sprache nicht ganz klar war. Intuitiv hatte ich schon eine Ahnung in welche Richtung die beiden Begriffe zeigen, aber der genaue Unterschied ist mir erst jetzt klar, wo ich die Begriffe nachgeschaut habe. Ich hätte ein Link auf eine Definition geschätzt, z.b. https://de.wikipedia.org/wiki/Einfache_Sprache, https://de.wikipedia.org/wiki/Leichte_Sprache oder gar eine Definition im Expander oder einem zweiten Expander. GTP-4o hat eine für mich gut verständliche Definition geliefert, mti dem Vorteil, dass die Begriffe nicht einzeln nachgeschaut werden müssen.

>Leichte Sprache
Definition: Leichte Sprache ist eine stark vereinfachte Form der deutschen Sprache, die nach bestimmten Regeln gestaltet wird, um Menschen mit kognitiven Einschränkungen, Lernschwierigkeiten oder geringen Sprachkenntnissen das Verstehen zu erleichtern.

>Merkmale:

>Kurze Sätze (meist nicht mehr als 8 Wörter).
Einfache Satzstrukturen, meist Hauptsätze.
Verzicht auf Fachbegriffe und Fremdwörter oder deren Erklärung.
Verwendung von einfachen Wörtern und Vermeidung von abstrakten Begriffen.
Direkte Ansprache und häufige Verwendung von persönlichen Pronomen.
Illustrationen und Piktogramme zur Unterstützung des Textverständnisses.
Geprüft von Prüfer*innen mit kognitiven Einschränkungen (z.B. durch das Netzwerk Leichte Sprache e.V.).
Zielgruppe: Menschen mit Lernschwierigkeiten, kognitiven Einschränkungen, Sprachbarrieren oder geringer Lesekompetenz.

>Einfache Sprache
Definition: Einfache Sprache ist weniger strikt als Leichte Sprache und zielt darauf ab, Texte für ein breiteres Publikum verständlicher zu machen, einschließlich Menschen mit niedriger Lesekompetenz, Nicht-Muttersprachlern oder Menschen mit begrenztem Bildungsniveau.

>Merkmale:

>Kürzere und klarere Sätze als in Standardtexten, aber weniger strikt als in Leichter Sprache.
Vereinfachte Satzstrukturen, aber auch Nebensätze können vorkommen.
Verwendung von allgemein verständlichen Wörtern und Begriffen, Fachbegriffe werden erklärt.
Weniger Redundanz und Präzisierung als in Leichter Sprache.
Ziel ist es, die Informationen klar und verständlich zu vermitteln, ohne den Inhalt zu stark zu reduzieren.
Zielgruppe: Menschen mit niedriger Lesekompetenz, Nicht-Muttersprachler, Menschen mit begrenztem Bildungsniveau oder wenig Zeit zum Lesen.

>Unterschiede im Detail
Striktheit der Regeln: Leichte Sprache folgt strikten Regeln, während Einfache Sprache flexibler ist.
Satzstruktur: Leichte Sprache verwendet fast ausschließlich Hauptsätze, Einfache Sprache kann auch Nebensätze verwenden.
Wortwahl: Leichte Sprache verzichtet weitgehend auf Fremdwörter und Fachbegriffe, während Einfache Sprache diese erklären kann.
Zielgruppen: Leichte Sprache ist speziell für Menschen mit kognitiven Einschränkungen konzipiert, während Einfache Sprache eine breitere Zielgruppe anspricht.
Fazit
Beide Ansätze haben ihre Berechtigung und spezifische Anwendungsbereiche. Leichte Sprache ist besonders wichtig für Menschen mit kognitiven Einschränkungen, während Einfache Sprache eine breitere Zielgruppe anspricht und allgemeine Texte verständlicher macht. Die Wahl zwischen beiden hängt von der Zielgruppe und dem Kontext ab, in dem der Text verwendet wird.

**Comment by rnckp** [comment]
Sehr gute Anregung. Ich werde entsprechende Erklärungen ergänzen. Das ergibt viel Sinn. Danke auch dafür!

**Comment by rnckp** [comment]
Erklärungen sind eingefügt. Danke nochmals für die Anregung.

**Comment by lcalmbach** [comment]
Lieber Patrick

vielen Dank für die superschnelle Umsetzung.
23 Sachen sind mir noch aufgefallen, sie sind zu unbedeutend, um
einen issue zu eröffnen, daher einfach per Mail.

1. Mir scheint im readme hat es keinen Link zur App, zumindest habe ich auf
die Schnelle keinen gefunden. Ich fände es praktisch, wenn man die App
rasch ausprobieren will und keine App installieren willl  oder kann.
Intuitiv habe ihc auf den Screendump der App geklickt in der Hoffnung es
wäre ein Link dahinter, der geht aber nur zum pgn, ich denke es wäre
sinnvoller den Link zur Applikation dahinter zu hängen.

2. Ich fände es gut wenn die beiden wichtigen Ausdrücke leichte/einfache
Sprache zumindest zu Beginn im Englisch Text übersetzt wären (simple and
plain languange) das sind auch stehende Begriffe und ich finde es immer
besser wenn man im Englischen deutsche Wörter verwendet, wenn man sie
übersetzt.

Wie gesagt, keine Biggies und ev. wirklich Geschmackssache.

Liebe Grüsse
Lukas

**Comment by rnckp** [comment]
Lieber Lukas

Danke für deine Nachricht und die weiteren Punkte!

Wir betreiben keine öffentliche Version der App. Wir bieten «lediglich» den Code als OSS und Anleitungen, wie man es sich schnell selbst einrichten kann. Von daher können wir leiden keinen direkten Link im Repo anbieten. 

Plain + Simple Language -> wird eingefügt! Es gibt gewissen Unterschiede. Aber darauf kann ich ja auch verweisen. 

Lieben Gruss und merci nochmals für alles!
