### ISSUE TITLE
Anzeige des CEFR im Diagramm

### ISSUE THREAD

**Issue by lcalmbach** [machinelearningZH/simply-simplify-language#6]
Das Diagramm der Verständlichkeit verschiedener Textarten ist sehr aussagekräftig. Toll fände ich, wenn auf der oberen X-Achse zusätzlich der CEFR angezeigt würde. Durch die Anzeige der Spannbreite verschiedener Textarten erhält man zwar ein gewisses Gefühl dafür, was die Punkte 0-20 bedeuten. Beim CEFR habe zumindest ich eine bessere Einschätzung dafür, was die verschiedenen Codes für die Sprachkomplexität bedeuten. Ihr übersetzt die Punktezahl bereits in einen CEFR-Code bei der Analyse, somit sollte die Übersetzung in der Grafik nicht schwierig sein.

Eventuell könnte man das Klexikon auch durch Kinderlexikon oder K(inder)lexikon ersetzen. Mir war der Begriff nicht geläufig, was natürlich nichts heißen soll, aber wenn es in der App schon um Vereinfachung geht, könnte man es in Betracht ziehen.

**Comment by rnckp** [comment]
Sehr gute Punkte. Merci! Nehme ich auf!

**Comment by rnckp** [comment]
Ist eingefügt. Danke nochmals.
