### ISSUE TITLE
ModuleNotFoundError: No module named 'mistralai.models.chat_completion'

### ISSUE THREAD

**Issue by Neluser** [machinelearningZH/simply-simplify-language#8]
Hello, I'm a newbie so I may be doing something wrong.

I get this error when I run the script “streamlit run sprache-vereinfachen.py”

I have tried reinstalling, changing the version of the mistralai module.
But unfortunately I get this problem every time.

The GPTo version runs without problems. “streamlit run sprache-vereinfachen_openai.py”

______

Hallo, ich bin ein Neuling, so kann ich etwas falsch machen.

Ich bekomme diesen Fehler, wenn ich das Skript „streamlit run sprache-vereinfachen.py“ ausführe.

Ich habe versucht, neu zu installieren und die Version des Mistralai-Moduls zu ändern.
Aber leider bekomme ich dieses Problem jedes Mal.

Die GPTo-Version läuft ohne Probleme. „streamlit run sprache-vereinfachen_openai.py“
___________________________________
System- Debian 12 (Proxmox VM)

ModuleNotFoundError: No module named 'mistralai.models.chat_completion'
Traceback:
File "/root/miniconda3/envs/simplify/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 85, in exec_func_with_error_handling
    result = func()
File "/root/miniconda3/envs/simplify/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 576, in code_to_exec
    exec(code, module.__dict__)
File "/root/simply-simplify-language/_streamlit_app/sprache-vereinfachen.py", line 36, in <module>
    from mistralai.models.chat_completion import ChatMessage

**Comment by rnckp** [comment]
Good catch. Mistral changed their Python client. I have to adapt the code. Let me look into that.

**Comment by Neluser** [comment]
Thank you so much for such a quick response.
Trying to fix it on my own has led me to complete failure. 
_(I attach a screenshot of the browser error)_
![image](https://github.com/user-attachments/assets/2ab895a9-e23b-471f-b697-c03110a5335d)

**Comment by rnckp** [comment]
No worries. I am on it. Should just take a couple of minutes.

**Comment by rnckp** [comment]
I just committed the fix. Can you pull the changes and try again?

**Comment by Neluser** [comment]
Thank you very much. Yeah, I'll try that now.

**Comment by Neluser** [comment]
It's working now!
Thank you. The problem can be closed. 
Have a good weekend.)

**Comment by rnckp** [comment]
Great! And you're welcome. Thank you for raising this issue. 👍

Have a great weekend too!
